[package]
name = "audiotools"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
walkdir = "2.5.0"
