[package]
name = "audiotools"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.20", features = ["cargo", "derive"] }
hound = "3.5.1"
rodio = "0.20.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
walkdir = "2.5.0"
